# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Develop

on:
  push:
    branches: [ "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Downloading repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install Packages
      run: npm ci
    - name: Building
      run: npm run build:dev
    - name: Testing
      run: npm run test:prod
    # - name: Deploying
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: dist/aba-angular/
